BUTTON_TEXT = {
    'en': {
        'back': "Back",
        'cancel': "Cancel",
        'change_basket_limit': "Change basket limit",
        'done': "Done",
        'help': "Help",
        'info': "Info",
        'main_menu': "Main menu",
        'normal': "Normal mode",
        'purchase_end': "End purchasing",
        'purchase_start': "Start purchasing",
        'settings': "Settings",
        'set_up_basket_limit': "Set up basket limit",
        'set_up_bot_mode': "Set up bot mode",
        'silent': "Silent mode",

    },
    'ru': {
        'back': "Назад",
        'cancel': "Отмена",
        'change_basket_limit': "Изменить лимит корзины",
        'done': "Готово",
        'help': "Помощь",
        'info': "Информация",
        'main_menu': "Основное меню",
        'normal': "Нормальный режим",
        'purchase_end': "Завершить покупку",
        'purchase_start': "Начать покупку",
        'settings': "Настройки",
        'set_up_basket_limit': "Установить лимит корзины",
        'set_up_bot_mode': "Установить режим работы бота",
        'silent': "Бесшумный режим",
    },
}
